### ISSUE TITLE
Pretrained Model 

### ISSUE THREAD

**Issue by abi98213** [srihari-humbarwadi/person_segmentation_tf2.0#1]
Hello!
Thank you very much for this great implementation. Can you share the pretrained weights for this model ?

**Comment by SuperMisswei** [comment]
I want it ,too.Looking forward to your reply .

**Comment by srihari-humbarwadi** [comment]
I will be releasing them in few days while. @SuperMisswei @mabdullahrafique

**Comment by SuperMisswei** [comment]
Thank you. I'm looking forward to it.






------------------ Original ------------------

**Comment by wangrong127** [comment]
Hi! Thank you for the great implementation. I also want the pretrained model. Looking forward to your reply.

**Comment by liminglang** [comment]
I want it too. Looking forward to your release.

**Comment by srihari-humbarwadi** [comment]
Here are the weights

https://drive.google.com/file/d/1d1Bw4_z-pE20Q0rfzTBPL_GON6_XPlcT/view?usp=drivesdk
@SuperMisswei @wangrong127 @liminglang @mabdullahrafique
