### ISSUE TITLE
What is your batch_size

### ISSUE THREAD

**Issue by liminglang** [srihari-humbarwadi/person_segmentation_tf2.0#4]
Thank you fot your reply. I am a fresher. Now,I am training model with GPU.The batch_size is 12.  Some results as follow:
![result](https://user-images.githubusercontent.com/27475169/69401503-31019500-0d30-11ea-8d49-9450ff339768.png)
 As shown in the figure，the accuracy and dice_coef is too high,but the epoch is low . Can you tell me why?
Looking forward to your reply。

**Comment by liminglang** [comment]
The resize_images length is 4850 and the validation images length is 861

**Comment by srihari-humbarwadi** [comment]
- I trained with a `batch_size` of 12
 - If you are using the `supervisely person dataset`, then the performance looks fine.

**Comment by liminglang** [comment]
> * I trained with a `batch_size` of 12
> * If you are using the `supervisely person dataset`, then the performance looks fine.
the dataset which i use was 'supervisely persion datatset' . the mask image is like this:
![man-white-shirt-male-person-159787](https://user-images.githubusercontent.com/27475169/69426536-72159b80-0d68-11ea-9a17-ea66c2c1a47e.png)。is it same as your?

**Comment by liminglang** [comment]
> * I trained with a `batch_size` of 12
> * If you are using the `supervisely person dataset`, then the performance looks fine.

I trained with a batch_size of 12 and the dataset was 'supervisely person dataset' too. But the result was too worse , just like this:
![girl-black-dress-portrait-hair-157606](https://user-images.githubusercontent.com/27475169/69475914-0980fa00-0e0e-11ea-9112-206716ba892b.png)
The mask images such as this:
![girl-eyes-makeup-sexy-60883](https://user-images.githubusercontent.com/27475169/69475973-a0e64d00-0e0e-11ea-88c8-bc840c4c573b.png)

What need to do with the dataset?
Would you like to share more information about this project？
looking forward to your reply，Sincerely grateful。

**Comment by charlizesmith** [comment]
@liminglang how'd you visualize the prediction after training. I don't know how to?
