### ISSUE TITLE
Why remove the regularization loss?

### ISSUE THREAD

**Issue by ellick53** [srihari-humbarwadi/person_segmentation_tf2.0#5]
In your last commit, you removed the regularization loss:

https://github.com/srihari-humbarwadi/person_segmentation_tf2.0/commit/3050a94f73e0bd1ed218e560fed8c610334bd35a

Why is that useful?
Thanks

**Comment by srihari-humbarwadi** [comment]
To know more about the this please follow my issue here
https://github.com/tensorflow/tensorflow/issues/33635
I will be pushing more commits to address this and release the newly trained weights as well

**Comment by ellick53** [comment]
That's pretty interesting, I had no idea of this problem. Does the bug really affect training, or is it more of an anti-pattern?

Thanks

**Comment by srihari-humbarwadi** [comment]
As you can see in the issue above, `model.losses == []` which means during training regularization losses don't contribute to the total loss, this was an oversight on my part. And also it's not the right way to do it

**Comment by ellick53** [comment]
I see, thanks for the explanation. Do you have any idea when you will push the fix?
