### ISSUE TITLE
What is the license status - Code reuse

### ISSUE THREAD

**Issue by ellick53** [srihari-humbarwadi/person_segmentation_tf2.0#6]
Hi, and thanks for sharing your work.

Is it alright to adapt your code for a research paper (I'll add a reference to this github)? 

If yes, you do need to add a license to your repo, though -> like
https://github.com/rishizek/tensorflow-deeplab-v3-plus/blob/master/LICENSE

Thanks!

**Comment by srihari-humbarwadi** [comment]
Yes, feel free to use it, I'll add a license soon

**Comment by ellick53** [comment]
Thanks.

**Comment by InternetMaster1** [comment]
Can this project be used for commercial purposes?

**Comment by ghost** [comment]
where is detection file?
please reply.

**Comment by srihari-humbarwadi** [comment]
Added License
