### ISSUE TITLE
Border artifacts?

### ISSUE THREAD

**Issue by ellick53** [srihari-humbarwadi/person_segmentation_tf2.0#7]
I get border artifacts like this:

![gdKO7](https://user-images.githubusercontent.com/49749099/74916628-7a608f80-53c6-11ea-9549-573c5f658ab5.png)

Any ideas what could be causing it? I'm using my dataset (~1000 annotated images of the same box, out of the same video sequence). Note that if I use bigger batches and train for more epochs, the borders tend to get thinner but never disappear. They also appear randomly around the image.

**Comment by srihari-humbarwadi** [comment]
This looks weird, can you try with a different rescaling factor before random cropping?

**Comment by ellick53** [comment]
I found why, I was messing with the preprocessing and at some point added this: 
image, mask = resize_with_crop_or_pad(image, mask, H, W)
This added a black border to all masks and flunked the training :|
