### ISSUE TITLE
pretrain model weights

### ISSUE THREAD

**Issue by Iceland-Leo** [srihari-humbarwadi/person_segmentation_tf2.0#9]
The url to the weights file is incorrect, could release the correct url of your pretrained model? Thank you very much!

**Comment by albertyou2** [comment]
@srihari-humbarwadi   I also want the pre-trained model ,thanks!

**Comment by Amshra267** [comment]
+1, provide the correct link, thanks in advance

**Comment by srihari-humbarwadi** [comment]
@Iceland-Leo @Amshra267 @albertyou2 
Please check the latest commit. I have included the weights as part of the repository it self
